/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

console.log("Taco Proxy index.js loading");

function getCookie(name) {
    const nameEQ = name + "=";
    const ca = document.cookie.split(';');
    for (let i = 0; i < ca.length; i++) {
        let c = ca[i];
        while (c.charAt(0) === ' ') {
            c = c.substring(1, c.length);
        }
        if (c.indexOf(nameEQ) === 0) {
            return decodeURIComponent(c.substring(nameEQ.length, c.length));
        }
    }
    return null;
}

document.title = getCookie("title");
document.getElementById("favicon").setAttribute("href", getCookie("icon"));

let tabs = [];
let activeTabId = null;

function updateNewTabButton() {
    let btn = document.getElementById('newTabBtn');
    if (btn) {
        btn.style.cursor = tabs.length >= 9 ? 'not-allowed' : 'pointer';
    }
}

function createTab(url = 'newtab.html', title = 'New Tab') {
    if (tabs.length >= 9) {
        alert("Max. 9 tabs allowed. \nWe are working on increasing this limit.");
        return;
    }
    let tabId = Date.now();
    tabs.push({ id: tabId, url, title, searchValue: 'taco://newtab' });
    updateNewTabButton();

    let tabDiv = document.createElement('div');
    tabDiv.className = 'tab';
    tabDiv.dataset.id = tabId;
    tabDiv.innerHTML = `<span>${title}</span><button class="close" title="Close tab"><i class="fa-solid fa-x"></i></button>`;
    tabDiv.draggable = true;
    tabDiv.addEventListener('dragstart', (e) => {
        e.dataTransfer.setData('text/plain', tabId);
    });
    tabDiv.addEventListener('click', () => switchTab(tabId));
    tabDiv.querySelector('.close').addEventListener('click', (e) => {
        e.stopPropagation();
        closeTab(tabId);
    });
    document.querySelector('.tabs').appendChild(tabDiv);

    let plusBtn = document.getElementById('newTabBtn');
    if (plusBtn) document.querySelector('.tabs').appendChild(plusBtn);

    let iframe = document.createElement('iframe');
    iframe.id = `iframe-${tabId}`;
    iframe.src = url;
    iframe.style.visibility = 'hidden';
    iframe.addEventListener('load', () => {
        let tab = tabs.find(t => t.id == tabId);
        if (tab) {
            tab.title = iframe.contentDocument.title || 'Untitled';
            document.querySelector(`.tab[data-id="${tabId}"] span`).textContent = tab.title;
            try {
                let newUrl = iframe.contentWindow.location.href;
                if (newUrl !== tab.url) {
                    tab.url = newUrl;
                    tab.searchValue = newUrl.includes('newtab.html') ? 'taco://newtab' : newUrl;
                }
            } catch (e) {}
            if (tabId === activeTabId) {
                document.getElementById('searchInput').value = tab.searchValue;
            }
        }
    });
    document.getElementById('content').appendChild(iframe);

    switchTab(tabId);
    return tabId;
}

function switchTab(tabId) {
    console.log('Switching to tab:', tabId, 'Active tabs:', tabs.map(t => t.id));

    document.querySelectorAll('#content iframe').forEach(ifr => ifr.style.visibility = 'hidden');
    document.getElementById(`iframe-${tabId}`).style.visibility = 'visible';
    document.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));
    document.querySelector(`.tab[data-id="${tabId}"]`).classList.add('active');
    activeTabId = tabId;
    document.querySelector(`.tab[data-id="${tabId}"]`).scrollIntoView({ behavior: 'smooth', block: 'nearest', inline: 'center' });

    const tab = tabs.find(t => t.id === tabId);
    if (tab) {
        document.getElementById('searchInput').value = tab.searchValue;
        console.log('Set searchInput to:', tab.searchValue, 'for tab', tabId);
        setTimeout(() => {
            document.getElementById('searchInput').value = tab.searchValue;
        }, 0);
    } else {
        console.log('Tab not found for id:', tabId);
    }

    tabs.forEach(tab => {
        let iframe = document.getElementById(`iframe-${tab.id}`);
        if (tab.id === tabId) {
            iframe.style.visibility = 'visible';
        } else {
            iframe.style.visibility = 'hidden';
        }
    });
}

function closeTab(tabId) {
    console.log('Closing tab:', tabId, 'Before filter, tabs:', tabs.map(t => t.id));
    document.querySelector(`.tab[data-id="${tabId}"]`).remove();
    document.getElementById(`iframe-${tabId}`).remove();
    tabs = tabs.filter(t => t.id !== tabId);
    console.log('After filter, tabs:', tabs.map(t => t.id));
    updateNewTabButton();
    if (activeTabId === tabId) {
        activeTabId = tabs.length ? tabs[0].id : null;
        console.log('New activeTabId:', activeTabId);
        if (activeTabId) {
            switchTab(activeTabId);
        } else {
            document.getElementById('searchInput').value = '';
            console.log('Cleared searchInput');
        }
    }
}

document.addEventListener('DOMContentLoaded', () => {
    let plusBtn = document.createElement('button');
    plusBtn.id = 'newTabBtn';
    plusBtn.innerHTML = '<i class="fa-solid fa-plus"></i>';
    plusBtn.title = 'New tab';
    plusBtn.addEventListener('click', () => createTab());
    document.querySelector('.tabs').appendChild(plusBtn);

    document.querySelector('.tabs').addEventListener('dragover', (e) => {
        e.preventDefault();
    });

    document.querySelector('.tabs').addEventListener('drop', (e) => {
        e.preventDefault();
        const draggedId = e.dataTransfer.getData('text/plain');
        const dropTarget = e.target.closest('.tab');
        if (dropTarget && dropTarget.dataset.id !== draggedId) {
            const draggedIndex = tabs.findIndex(t => t.id == draggedId);
            const dropIndex = tabs.findIndex(t => t.id == dropTarget.dataset.id);
            if (draggedIndex !== -1 && dropIndex !== -1) {
                const [draggedTab] = tabs.splice(draggedIndex, 1);
                tabs.splice(dropIndex, 0, draggedTab);
                const draggedElement = document.querySelector(`.tab[data-id="${draggedId}"]`);
                const dropElement = dropTarget;
                document.querySelector('.tabs').insertBefore(draggedElement, dropElement);
            }
        }
    });

    createTab();

    document.getElementById('settingsBtn').addEventListener('click', () => {
        let iframe = document.createElement('iframe');
        iframe.src = 'settings.html';
        iframe.style.position = 'absolute';
        iframe.style.top = '0';
        iframe.style.left = '0';
        iframe.style.width = '100%';
        iframe.style.height = '100%';
        iframe.style.zIndex = '1000';
        iframe.style.border = 'none';
        document.body.appendChild(iframe);
    });

    window.closeSettingsIframe = () => {
        let iframes = document.querySelectorAll('iframe[src="settings.html"]');
        iframes.forEach(ifr => document.body.removeChild(ifr));
    };

    document.getElementById('prevPage').addEventListener('click', () => {
        if (activeTabId) {
            try {
                document.getElementById(`iframe-${activeTabId}`).contentWindow.history.back();
            } catch (e) {}
        }
    });
    document.getElementById('nextPage').addEventListener('click', () => {
        if (activeTabId) {
            try {
                document.getElementById(`iframe-${activeTabId}`).contentWindow.history.forward();
            } catch (e) {}
        }
    });
    document.getElementById('refresh').addEventListener('click', () => {
        if (activeTabId) {
            let iframe = document.getElementById(`iframe-${activeTabId}`);
            iframe.src = iframe.src;
        }
    });

    let searchInput = document.getElementById("searchInput");
    let searchBtn = document.getElementById("searchBtn");
    searchBtn.addEventListener("click", function() {
        let query = searchInput.value;
        if (query) {
            if (!query.startsWith("http://") && !query.startsWith("https://") && !query.startsWith("www.")) {
                query = "https://www.google.com/search?q=" + encodeURIComponent(query);
            }
            if (activeTabId) {
                let iframe = document.getElementById(`iframe-${activeTabId}`);
                iframe.src = query;
                let tab = tabs.find(t => t.id === activeTabId);
                if (tab) {
                    tab.url = query;
                    tab.searchValue = query;
                }
            }
        }
    });
    searchInput.addEventListener("keydown", function(event) {
        if (event.key === "Enter") {
            searchBtn.click();
            searchInput.blur();
        }
    });
    document.getElementById('searchInput').addEventListener('input', () => {
        if (activeTabId) {
            const tab = tabs.find(t => t.id === activeTabId);
            if (tab) tab.searchValue = document.getElementById('searchInput').value;
        }
    });
});

console.log("------------PLEASE NOTE------------");
console.log("Taco Proxy is still in active development.");
console.log("To lighten the workload on our servers, ");
console.log("Taco Proxy will limit the amount of maximum tabs open at once to 9.");
console.log("We are currently working on increasing this limit. This is only temporary.");
console.log("For support, visit: [insert support URL here]");
console.log("-----------------------------------");
console.log("Taco Proxy index.js finished loading");